export const APPROVAL_GRAPH_URL = process.env.APPROVAL_GRAPH_URL || 'MISSING REQUIRED ENV VAR';
export const SCAN_DATA = process.env.SCAN_DATA || 'MISSING REQUIRED ENV VAR';
export const WATCHLIST_DATA = process.env.WATCHLIST_DATA || 'MISSING REQUIRED ENV VAR';
export const MONITOR_ID = process.env.MONITOR_ID || 'MISSING REQUIRED ENV VAR';
export const START_BLOCK = process.env.START_BLOCK || 'MISSING REQUIRED ENV VAR';
export const WEBHOOK_URL = process.env.WEBHOOK_URL || 'MISSING REQUIRED ENV VAR';
export const WEBHOOK_ROLE = process.env.WEBHOOK_ROLE || 'MISSING REQUIRED ENV VAR';
